-- CreateTable
CREATE TABLE `SubmissionService` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `problemId` INTEGER NOT NULL,
    `code` VARCHAR(191) NOT NULL,
    `language` ENUM('CPP', 'PYTHON') NOT NULL,
    `status` ENUM('PENDING', 'RUNNING', 'ACCEPTED', 'WRONG_ANSWER') NOT NULL DEFAULT 'PENDING',
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
